// Pełna lista zawodów i specjalizacji medycznych używana w aplikacji
// - alfabetycznie po label (język polski)
// - value bez polskich znaków (snake_case)

export const MEDICAL_PROFESSIONS_FULL = [
  { value: 'alergolog', label: 'Alergolog' },
  { value: 'alergolog_dzieciecy', label: 'Alergolog dziecięcy' },
  { value: 'androlog', label: 'Androlog' },
  { value: 'anestezjolog', label: 'Anestezjolog' },
  { value: 'angiochirurg', label: 'Angiochirurg' },
  { value: 'angiolog', label: 'Angiolog' },
  { value: 'asystent_weterynaryjny', label: 'Asystent weterynaryjny' },
  { value: 'audiolog_foniatra', label: 'Audiolog/foniatra' },
  { value: 'bariatra', label: 'Bariatra' },
  { value: 'chirurg', label: 'Chirurg' },
  { value: 'chirurg_dzieciecy', label: 'Chirurg dziecięcy' },
  { value: 'chirurg_naczyniowy', label: 'Chirurg naczyniowy' },
  { value: 'chirurg_onkologiczny', label: 'Chirurg onkologiczny' },
  { value: 'chirurg_plastyczny', label: 'Chirurg plastyczny' },
  { value: 'chirurg_stomatologiczny', label: 'Chirurg stomatologiczny' },
  { value: 'chirurg_szczekowo_twarzowy', label: 'Chirurg szczękowo-twarzowy' },
  { value: 'dermatolog', label: 'Dermatolog' },
  { value: 'dermatolog_dzieciecy', label: 'Dermatolog dziecięcy' },
  { value: 'diabetolog', label: 'Diabetolog' },
  { value: 'diabetolog_dzieciecy', label: 'Diabetolog dziecięcy' },
  { value: 'diagnosta_laboratoryjny', label: 'Diagnosta laboratoryjny' },
  { value: 'dietetyk', label: 'Dietetyk' },
  { value: 'endokrynolog', label: 'Endokrynolog' },
  { value: 'endokrynolog_dzieciecy', label: 'Endokrynolog dziecięcy' },
  { value: 'ergoterapeuta', label: 'Ergoterapeuta' },
  { value: 'farmaceuta', label: 'Farmaceuta' },
  { value: 'fizjoterapeuta', label: 'Fizjoterapeuta' },
  { value: 'flebolog', label: 'Flebolog' },
  { value: 'gastrolog', label: 'Gastrolog' },
  { value: 'gastrolog_dzieciecy', label: 'Gastrolog dziecięcy' },
  { value: 'genetyk', label: 'Genetyk' },
  { value: 'geriatra', label: 'Geriatra' },
  { value: 'ginekolog', label: 'Ginekolog' },
  { value: 'ginekolog_dzieciecy', label: 'Ginekolog dziecięcy' },
  { value: 'ginekolog_onkologiczny', label: 'Ginekolog onkologiczny' },
  { value: 'hematolog', label: 'Hematolog' },
  { value: 'hematolog_dzieciecy', label: 'Hematolog dziecięcy' },
  { value: 'hepatolog', label: 'Hepatolog' },
  { value: 'higienistka_stomatologiczna', label: 'Higienistka stomatologiczna' },
  { value: 'hipertensjolog', label: 'Hipertensjolog' },
  { value: 'immunolog', label: 'Immunolog' },
  { value: 'internista', label: 'Internista' },
  { value: 'kardiochirurg', label: 'Kardiochirurg' },
  { value: 'kardiolog', label: 'Kardiolog' },
  { value: 'kardiolog_dzieciecy', label: 'Kardiolog dziecięcy' },
  { value: 'kosmetolog', label: 'Kosmetolog' },
  { value: 'laryngolog', label: 'Laryngolog' },
  { value: 'laryngolog_dzieciecy', label: 'Laryngolog dziecięcy' },
  { value: 'lekarz_bez_specjalizacji', label: 'Lekarz bez specjalizacji' },
  { value: 'lekarz_chorob_zakaznych', label: 'Lekarz chorób zakaźnych' },
  { value: 'lekarz_medycyny_estetycznej', label: 'Lekarz medycyny estetycznej' },
  { value: 'lekarz_medycyny_nuklearnej', label: 'Lekarz medycyny nuklearnej' },
  { value: 'lekarz_medycyny_paliatywnej', label: 'Lekarz medycyny paliatywnej' },
  { value: 'lekarz_medycyny_pracy', label: 'Lekarz medycyny pracy' },
  { value: 'lekarz_rehabilitacji_medycznej', label: 'Lekarz rehabilitacji medycznej' },
  { value: 'lekarz_rodzinny', label: 'Lekarz rodzinny' },
  { value: 'lekarz_sportowy', label: 'Lekarz sportowy' },
  { value: 'lekarz_w_trakcie_specjalizacji', label: 'Lekarz w trakcie specjalizacji' },
  { value: 'lekarz_weterynarii', label: 'Lekarz weterynarii' },
  { value: 'logopeda', label: 'Logopeda' },
  { value: 'neonatolog', label: 'Neonatolog' },
  { value: 'nefrolog', label: 'Nefrolog' },
  { value: 'nefrolog_dzieciecy', label: 'Nefrolog dziecięcy' },
  { value: 'neurochirurg', label: 'Neurochirurg' },
  { value: 'neurolog', label: 'Neurolog' },
  { value: 'neurolog_dzieciecy', label: 'Neurolog dziecięcy' },
  { value: 'okulista', label: 'Okulista' },
  { value: 'okulista_dzieciecy', label: 'Okulista dziecięcy' },
  { value: 'onkolog', label: 'Onkolog' },
  { value: 'onkolog_dzieciecy', label: 'Onkolog dziecięcy' },
  { value: 'opiekun_medyczny', label: 'Opiekun medyczny' },
  { value: 'optometrysta', label: 'Optometrysta' },
  { value: 'ortodonta', label: 'Ortodonta' },
  { value: 'ortopeda', label: 'Ortopeda' },
  { value: 'ortopeda_dzieciecy', label: 'Ortopeda dziecięcy' },
  { value: 'osteopata', label: 'Osteopata' },
  { value: 'perfuzjonista', label: 'Perfuzjonista' },
  { value: 'periodontolog', label: 'Periodontolog' },
  { value: 'pielegniarka', label: 'Pielęgniarka/Pielęgniarz' },
  { value: 'polozna', label: 'Położna/Położny' },
  { value: 'proktolog', label: 'Proktolog' },
  { value: 'protetyk', label: 'Protetyk' },
  { value: 'protetyk_sluchu', label: 'Protetyk słuchu' },
  { value: 'protetyk_stomatologiczny', label: 'Protetyk stomatologiczny' },
  { value: 'psychiatra', label: 'Psychiatra' },
  { value: 'psychiatra_dzieciecy', label: 'Psychiatra dziecięcy' },
  { value: 'psychoonkolog', label: 'Psychoonkolog' },
  { value: 'psycholog', label: 'Psycholog' },
  { value: 'psycholog_dzieciecy', label: 'Psycholog dziecięcy' },
  { value: 'psychoterapeuta', label: 'Psychoterapeuta' },
  { value: 'psychotraumatolog', label: 'Psychotraumatolog' },
  { value: 'pulmonolog', label: 'Pulmonolog' },
  { value: 'pulmonolog_dzieciecy', label: 'Pulmonolog dziecięcy' },
  { value: 'radiolog', label: 'Radiolog' },
  { value: 'ratownik_medyczny', label: 'Ratownik medyczny' },
  { value: 'reumatolog', label: 'Reumatolog' },
  { value: 'reumatolog_dzieciecy', label: 'Reumatolog dziecięcy' },
  { value: 'seksuolog', label: 'Seksuolog' },
  { value: 'specjalista_medycyny_naturalnej', label: 'Specjalista medycyny naturalnej' },
  { value: 'stomatolog', label: 'Stomatolog' },
  { value: 'stomatolog_dzieciecy', label: 'Stomatolog dziecięcy' },
  { value: 'technik_dentystyczny', label: 'Technik dentystyczny' },
  { value: 'technik_farmaceutyczny', label: 'Technik farmaceutyczny' },
  { value: 'technik_medycyny_nuklearnej', label: 'Technik medycyny nuklearnej' },
  { value: 'technik_ortopedyczny', label: 'Technik ortopedyczny' },
  { value: 'technik_weterynarii', label: 'Technik weterynarii' },
  { value: 'terapeuta', label: 'Terapeuta' },
  { value: 'terapeuta_zajeciowy', label: 'Terapeuta zajęciowy' },
  { value: 'ultrasonografista', label: 'Ultrasonografista' },
  { value: 'urolog', label: 'Urolog' },
  { value: 'urolog_dzieciecy', label: 'Urolog dziecięcy' },
  { value: 'wenerolog', label: 'Wenerolog' },
  { value: 'zoofizjoterapeuta', label: 'Zoofizjoterapeuta' },
] as const;

// Zgodność wsteczna i skróty
export const MEDICAL_PROFESSIONS = MEDICAL_PROFESSIONS_FULL;
export const MEDICAL_FIELDS = MEDICAL_PROFESSIONS_FULL;
export const EXTENDED_MEDICAL_PROFESSIONS = MEDICAL_PROFESSIONS_FULL;

// 10 największych grup (szybki wybór)
export const MEDICAL_PROFESSIONS_10 = [
  { value: 'lekarz_rodzinny', label: 'Lekarz rodzinny' },
  { value: 'pielegniarka', label: 'Pielęgniarka/Pielęgniarz' },
  { value: 'fizjoterapeuta', label: 'Fizjoterapeuta' },
  { value: 'farmaceuta', label: 'Farmaceuta' },
  { value: 'stomatolog', label: 'Stomatolog' },
  { value: 'ratownik_medyczny', label: 'Ratownik medyczny' },
  { value: 'diagnosta_laboratoryjny', label: 'Diagnosta laboratoryjny' },
  { value: 'psycholog', label: 'Psycholog' },
  { value: 'lekarz_weterynarii', label: 'Lekarz weterynarii' },
  { value: 'kosmetolog', label: 'Kosmetolog' },
] as const;

export const EMPLOYMENT_TYPES = [
  { value: 'umowa_o_prace', label: 'Umowa o pracę' },
  { value: 'umowa_zlecenie', label: 'Umowa zlecenie' },
  { value: 'umowa_o_dzielo', label: 'Umowa o dzieło' },
  { value: 'b2b', label: 'Współpraca B2B' },
  { value: 'praktyka', label: 'Praktyka / Staż' },
  { value: 'wolontariat', label: 'Wolontariat' },
] as const;

export const EXPERIENCE_LEVELS = [
  { value: 'junior', label: 'Junior (0-2 lata)' },
  { value: 'mid', label: 'Mid (2-5 lat)' },
  { value: 'senior', label: 'Senior (5+ lat)' },
  { value: 'lead', label: 'Lead / Kierownik' },
  { value: 'student', label: 'Student / Absolwent' },
] as const;

export type MedicalProfession10 = typeof MEDICAL_PROFESSIONS_10[number]['value'];
export type MedicalProfession = typeof MEDICAL_PROFESSIONS[number]['value'];
export type ExtendedMedicalProfession = typeof EXTENDED_MEDICAL_PROFESSIONS[number]['value'];
export type EmploymentType = typeof EMPLOYMENT_TYPES[number]['value'];
export type ExperienceLevel = typeof EXPERIENCE_LEVELS[number]['value'];

